<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\School;

class BillGroupSeeder extends Seeder
{
    public function run()
    {
        $smp = School::where('name', 'SMP Al Bahjah')->first();
        $sma = School::where('name', 'SMA Al Bahjah')->first();

        if (!$smp) {
            throw new \Exception("Sekolah 'SMP Al Bahjah' tidak ditemukan.");
        }

        if (!$sma) {
            throw new \Exception("Sekolah 'SMA Al Bahjah' tidak ditemukan.");
        }

        DB::table('bill_groups')->insert([
            [
                'type' => 'periode',
                'name' => 'SPP Angkatan 2022',
                'level_id' => null,
                'grade_id' => 3,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => 12,
                'amount_per_tagihan' => 1525000,
                'start_date' => '2024-07-01',
                'end_date' => '2025-06-30',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'periode',
                'name' => 'SPP Angkatan 2023',
                'level_id' => null,
                'grade_id' => 2,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => 12,
                'amount_per_tagihan' => 1625000,
                'start_date' => '2024-07-01',
                'end_date' => '2025-06-30',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'Formulir Pendaftaran',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 400000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'DU Santri Baru SMPIQu 2024',
                'level_id' => null,
                'grade_id' => 1,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 16700000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'Daftar Ulang Kenaikan Kelas 2024',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $smp->id,
                'academic_year' => '2023-2024',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 4020000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'periode',
                'name' => 'SPP Angkatan 2024',
                'level_id' => null,
                'grade_id' => 1,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => 12,
                'amount_per_tagihan' => 1700000,
                'start_date' => '2024-07-01',
                'end_date' => '2025-06-30',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'Formulir Pendaftaran',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $sma->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 400000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'DU Santri Baru SMAIQu',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $sma->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 17000000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'DU Santri Baru - SMPIQu 2025',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $smp->id,
                'academic_year' => '2025-2026',
                'gender' => null,
                'tagihan_count' => null,
                'amount_per_tagihan' => 17000000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'periode',
                'name' => 'SPP Angkatan 2025',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $smp->id,
                'academic_year' => '2025-2026',
                'gender' => null,
                'tagihan_count' => 12,
                'amount_per_tagihan' => 1850000,
                'start_date' => '2025-07-01',
                'end_date' => '2026-06-30',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'DU Kenaikan Kelas Tahun 2025 - Angkatan 2024',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 4500000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'event',
                'name' => 'DU Kenaikan Kelas Tahun 2025 - Angkatan 2023',
                'level_id' => null,
                'grade_id' => null,
                'school_id' => $smp->id,
                'academic_year' => '2024-2025',
                'gender' => 'male',
                'tagihan_count' => null,
                'amount_per_tagihan' => 4020000,
                'start_date' => null,
                'end_date' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
