<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GlAccount;

class GlAccountSeeder extends Seeder
{
    public function run(): void
    {
        GlAccount::insert([
[
        'code' => '100000',
        'name' => 'KAS',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110101',
        'name' => 'KAS BANK - YAYASAN AL BAHJAH CAB. BOGOR 7771111089',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110102',
        'name' => 'KAS BANK - YAYASAN AL BAHJAH BOGOR 7236931352',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110103',
        'name' => 'KAS BANK - WAQAF AL BAHJAH BOGOR 7778882242',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110104',
        'name' => 'KAS BANK - INFAQ PRODUKTIF LPD AL BAHJAH 7775550028',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110105',
        'name' => 'KAS BANK - INFAQ PRODUKTIF AL BAHJAH BOGOR 7512221143',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110106',
        'name' => 'KAS BANK - LPD AL BAHJAH 7512226668',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110107',
        'name' => 'KAS BANK - INFAQ JUMAT BERKAH 7263087121',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110110',
        'name' => 'KAS BANK - MAULID ABBOGOR 7252545567',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110111',
        'name' => 'KAS BANK - DANA ABADI AB 7895988884',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110112',
        'name' => 'KAS BANK - DANA ABADI UMAT 7895899997',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110201',
        'name' => 'KAS BANK - SMPIQU AL BAHJAH BOGOR PSB 7236928998',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110202',
        'name' => 'KAS BANK - SMPIQU AL BAHJAH BOGOR SPP 7236929617',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110203',
        'name' => 'KAS BANK - SMPIQU AL BAHJAH BOGOR DU 7236929285',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110204',
        'name' => 'KAS BANK - BEKAL SMPIQU AL BAHJAH BOGOR 7236930507',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110205',
        'name' => 'KAS BANK - SMPIQU AL BAHJAH BOGOR OPRS 7236929797',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110206',
        'name' => 'KAS BANK - INFAQ SMPIQU AL BAHJAH BOGOR 7236930194',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110207',
        'name' => 'KAS BANK - SMPIQU ALBAHJAH BOGOR SPP 7514443801',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110208',
        'name' => 'KAS BANK - SMPIQU ALBAHJAH BOGOR DU 7514443798',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110209',
        'name' => 'KAS BANK - BEKAL SMPIQU ALBAHJAH BOGOR 7203734098',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110210',
        'name' => 'KAS BANK -1 SMPIQU AL BAHJAH BOGOR OPRS',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110211',
        'name' => 'KAS BANK - SISA ANGGARAN FORMAL 7263087547',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110301',
        'name' => 'KAS BANK - OPS TAHFIDZ AB BOGOR 7514445766',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110302',
        'name' => 'KAS BANK - SAHABAT SANTRI AL BAHJAH BGR DLL 7775550036',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110401',
        'name' => 'KAS BANK - SYIRKAH YAYASAN AL BAHJAH BOGOR 7236930763',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110402',
        'name' => 'KAS BANK - SYIRKAH YAYASAN AL BAHJAH BOGOR 7514445251',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110403',
        'name' => 'KAS BANK - VOUCHER PEJUANG YAYASAN AL BAHJAH 7252543001',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110404',
        'name' => 'KAS BANK - OTO AL BAHJAH BOGOR 7293133098',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110405',
        'name' => 'KAS BANK - BELAJAR BERSAMA BUYA AL BAHJAH BGR 729484766',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110501',
        'name' => 'KAS BANK - CATERING YAYASAN AL BAHJAH BOGOR 7236930992',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110502',
        'name' => 'KAS BANK - CATERING YAYASAN ALBAHJAH BOGOR 7514445278',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110601',
        'name' => 'KAS BANK - LAUNDRY YAYASAN AL BAHJAH BOGOR 7236931198',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110701',
        'name' => 'KAS BANK - POSKESTREN YAYASAN AL BAHJAH BOGOR 7240880924',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110702',
        'name' => 'KAS BANK - POSKESTREN YAYASAN AL BAHJAH BOGOR 7514445286',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110801',
        'name' => 'KAS BANK - MEDIA AL BAHJAH BOGOR 7779994419',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110802',
        'name' => 'KAS BANK - INFAQ ALAT MEDIA AL BAHJAH BOGOR 7293132903',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110901',
        'name' => 'KAS BANK - BAGI HASIL DIV EKONOMI AB BGR 7514445723',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '110902',
        'name' => 'KAS BANK - LABA UNIT USAHA AL BAHJAH BOGOR 7263086637',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '111001',
        'name' => 'KAS BANK - ICE CREAMQU 7265525045',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '111002',
        'name' => 'KAS BANK - AL BAHJAH STORE 7252547511',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '120110',
        'name' => 'PIUTANG USAHA - DU',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '120120',
        'name' => 'PIUTANG USAHA - SPP',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '120130',
        'name' => 'PIUTANG USAHA - PSB',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '120140',
        'name' => 'PIUTANG USAHA - PIHAK KETIGA',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '120210',
        'name' => 'PIUTANG USAHA - PIHAK BERELASI',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '130120',
        'name' => 'PIUTANG LAIN-LAIN - PEJUANG',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '130130',
        'name' => 'PIUTANG LAIN-LAIN - VOUCHER',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '130110',
        'name' => 'PIUTANG LAIN-LAIN - PIHAK BERELASI',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '130140',
        'name' => 'PIUTANG LAIN-LAIN - SHAREHOLDER',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '140110',
        'name' => 'BARANG JADI - SYIRKAH',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '140120',
        'name' => 'BARANG JADI - KANTIN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '140210',
        'name' => 'BAHAN MENTAH - SAYUR',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '140220',
        'name' => 'BAHAN MENTAH - SEMBAKO',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '140310',
        'name' => 'BAHAN MENTAH - SABUN LAUNDRY',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '140410',
        'name' => 'SUPPLIES',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170000',
        'name' => 'CIP',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170010',
        'name' => 'NILAI PEROLEHAN ASET TETAP - TANAH',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170020',
        'name' => 'NILAI PEROLEHAN ASET TETAP - BANGUNAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170030',
        'name' => 'NILAI PEROLEHAN ASET TETAP - FURNITUR',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170040',
        'name' => 'NILAI PEROLEHAN ASET TETAP - KOMPUTER DAN PERALATAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170050',
        'name' => 'NILAI PEROLEHAN ASET TETAP - KENDARAAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170060',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERALATAN DAPUR',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170070',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERALATAN LAUNDRY',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170080',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERALATAN POSKES',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170090',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERALATAN SYIRKAH',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170100',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERALATAN KANTIN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170110',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERKAKAS',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '170120',
        'name' => 'NILAI PEROLEHAN ASET TETAP - PERALATAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171020',
        'name' => 'AKUMULASI PENYUSUTAN - BANGUNAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171030',
        'name' => 'AKUMULASI PENYUSUTAN - FURNITUR',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171040',
        'name' => 'AKUMULASI PENYUSUTAN - KOMPUTER DAN PERALATAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171050',
        'name' => 'AKUMULASI PENYUSUTAN - KENDARAAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171060',
        'name' => 'AKUMULASI PENYUSUTAN - PERALATAN DAPUR',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171070',
        'name' => 'AKUMULASI PENYUSUTAN - PERALATAN LAUNDRY',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171080',
        'name' => 'AKUMULASI PENYUSUTAN - PERALATAN POSKES',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171090',
        'name' => 'AKUMULASI PENYUSUTAN - PERALATAN SYIRKAH',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171100',
        'name' => 'AKUMULASI PENYUSUTAN - PERALATAN KANTIN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171110',
        'name' => 'AKUMULASI PENYUSUTAN - PERKAKAS',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '171120',
        'name' => 'AKUMULASI PENYUSUTAN - PERALATAN',
        'type' => 'asset',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '230210',
        'name' => 'SALDO VOUCHER PEJUANG',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '220110',
        'name' => 'UTANG USAHA - PIHAK BERELASI',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '220120',
        'name' => 'UTANG USAHA - PIHAK KETIGA',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '220210',
        'name' => 'UTANG LAIN-LAIN - PIHAK BERELASI',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '220220',
        'name' => 'UTANG LAIN-LAIN - PIHAK KETIGA',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '230110',
        'name' => 'SALDO BEKAL SANTRI',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '230120',
        'name' => 'PENDAPATAN DITANGGUHKAN',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '230310',
        'name' => 'ZAKAT MAAL',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '260110',
        'name' => 'UTANG JANGKA PANJANG - PIHAK KETIGA',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '260200',
        'name' => 'UTANG BANK',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '270110',
        'name' => 'LEASE - KENDARAAN',
        'type' => 'liability',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '300000',
        'name' => 'EKUITAS',
        'type' => 'equity',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '320000',
        'name' => 'MODAL DISETOR',
        'type' => 'equity',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '330000',
        'name' => 'LABA DITAHAN - BEG',
        'type' => 'equity',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '330001',
        'name' => 'LABA DITAHAN',
        'type' => 'equity',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '410010',
        'name' => 'PENDAPATAN - SMPIQU DU',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '410020',
        'name' => 'PENDAPATAN - SMPIQU SPP',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '410030',
        'name' => 'PENDAPATAN - SMPIQU PSB',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '410040',
        'name' => 'PENDAPATAN - SMPIQU OTHERS',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '410050',
        'name' => 'PENDAPATAN - SMPIQU INFAQ',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '410060',
        'name' => 'PENDAPATAN - SMPIQU TAHFIDZ SPP',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '420010',
        'name' => 'PENDAPATAN - CATERING',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '430010',
        'name' => 'PENDAPATAN - LAUNDRY',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '440010',
        'name' => 'PENDAPATAN - SYIRKAH MART',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '440020',
        'name' => 'PENDAPATAN - KANTIN',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450111',
        'name' => 'PENDAPATAN - WAKAF AL BAHJAH (WAKAF)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450112',
        'name' => 'PENDAPATAN - LPD AL BAHJAH (WAKAF)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450121',
        'name' => 'PENDAPATAN - YAYASAN AB BOGOR (INFAQ OPERASIONAL)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450122',
        'name' => 'PENDAPATAN - INPRO LPD (INFAQ)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450123',
        'name' => 'PENDAPATAN - INPRO BOGOR (INFAQ)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450124',
        'name' => 'PENDAPATAN - INFAQ JUMAT BERKAH (INFAQ)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450125',
        'name' => 'PENDAPATAN - SAHABAT SANTRI (MEALS)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450126',
        'name' => 'PENDAPATAN - TAHFIDZ (INFAQ)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450127',
        'name' => 'PENDAPATAN - MAULID AB BOGOR',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450128',
        'name' => 'PENDAPATAN - DANA ABADI UMAT',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450210',
        'name' => 'PENDAPATAN - PROFIT SHARING',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '450220',
        'name' => 'PENDAPATAN - LEBAK BULUS (INFAQ)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '460110',
        'name' => 'PENDAPATAN - MEDIA (INFAQ)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '460120',
        'name' => 'PENDAPATAN - MEDIA (OTHER)',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '470110',
        'name' => 'PENDAPATAN - QURBAN',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '480010',
        'name' => 'PENDAPATAN - POSKESTREN',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501010',
        'name' => 'HPP - BARANG JADI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501020',
        'name' => 'HPP - GAS',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501030',
        'name' => 'HPP - BAHAN MENTAH',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501040',
        'name' => 'HPP - SAYUR',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501050',
        'name' => 'HPP - SEMBAKO',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501060',
        'name' => 'HPP - LAUNDRY',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501070',
        'name' => 'HPP - JASA MEDIS',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501080',
        'name' => 'HPP - OBAT-OBATAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501090',
        'name' => 'HPP - MERCHANDISE',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '501100',
        'name' => 'HPP - QURBAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '503010',
        'name' => 'HPP - BAGI HASIL QURBAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601010',
        'name' => 'BEBAN KARYAWAN - GAJI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601020',
        'name' => 'BEBAN KARYAWAN - VOUCHER',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601030',
        'name' => 'BEBAN KARYAWAN - AB SEHAT',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601040',
        'name' => 'BEBAN KARYAWAN - THR',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601050',
        'name' => 'BEBAN KARYAWAN - MEALS',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601060',
        'name' => 'BEBAN KARYAWAN - HOUSING',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601070',
        'name' => 'BEBAN KARYAWAN - UNIFORM',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601080',
        'name' => 'BEBAN KARYAWAN - GATHERING',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601090',
        'name' => 'BEBAN KARYAWAN - TRAINING',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601100',
        'name' => 'BEBAN KARYAWAN - LAINNYA',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '601110',
        'name' => 'BEBAN KARYAWAN - RAKER',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602010',
        'name' => 'BEBAN SANTRI - CATERING',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602020',
        'name' => 'BEBAN SANTRI - LAUNDRY',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602030',
        'name' => 'BEBAN SANTRI - AB SEHAT',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602040',
        'name' => 'BEBAN SANTRI - BUKU',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602050',
        'name' => 'BEBAN SANTRI - PERALATAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602060',
        'name' => 'BEBAN SANTRI - SERAGAM SEKOLAH',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602070',
        'name' => 'BEBAN SANTRI - KEGIATAN SANTRI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '602080',
        'name' => 'BEBAN SANTRI - UJIAN DAN EVALUASI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '603010',
        'name' => 'BEBAN JASA DAN PERAWATAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '604010',
        'name' => 'BEBAN MARKETING DAN PROMOSI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '604020',
        'name' => 'BEBAN KOMISI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '605010',
        'name' => 'BEBAN EVENT - KEGIATAN YAYASAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '605020',
        'name' => 'BEBAN EVENT - KEGIATAN KEAGAMAAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '605030',
        'name' => 'BEBAN EVENT - KEGIATAN SEKOLAH',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '605040',
        'name' => 'BEBAN EVENT - KEGIATAN SANTRI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '605050',
        'name' => 'BEBAN EVENT - TEACHER ACTIVITY',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '606010',
        'name' => 'BEBAN UMUM DAN ADMINISTRASI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '607010',
        'name' => 'BEBAN KETAMUAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '608010',
        'name' => 'BEBAN IT',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '609010',
        'name' => 'BEBAN SEWA',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '610010',
        'name' => 'BEBAN TRANSPORTASI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '611010',
        'name' => 'BEBAN UTILITAS - LISTRIK',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '611020',
        'name' => 'BEBAN UTILITAS - INTERNET DAN TELEPON',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '611030',
        'name' => 'BEBAN UTILITAS - SANITASI',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612020',
        'name' => 'BEBAN DEPRESIASI - BANGUNAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612030',
        'name' => 'BEBAN DEPRESIASI - FURNITUR',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612040',
        'name' => 'BEBAN DEPRESIASI - KOMPUTER DAN PERALATAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612050',
        'name' => 'BEBAN DEPRESIASI - KENDARAAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612060',
        'name' => 'BEBAN DEPRESIASI - PERALATAN DAPUR',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612070',
        'name' => 'BEBAN DEPRESIASI - PERALATAN LAUNDRY',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612080',
        'name' => 'BEBAN DEPRESIASI - PERALATAN POSKES',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612090',
        'name' => 'BEBAN DEPRESIASI - PERALATAN SYIRKAH',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612100',
        'name' => 'BEBAN DEPRESIASI - PERALATAN KANTIN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612110',
        'name' => 'BEBAN DEPRESIASI - PERKAKAS',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '612120',
        'name' => 'BEBAN DEPRESIASI - PERALATAN',
        'type' => 'expense',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '711000',
        'name' => 'PENDAPATAN SUBSIDI',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '712000',
        'name' => 'PENDAPATAN BAGI HASIL',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '713000',
        'name' => 'PENDAPATAN LAIN-LAIN',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '721000',
        'name' => 'BEBAN SUBSIDI',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '722000',
        'name' => 'BEBAN DONASI',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '723000',
        'name' => 'BEBAN ADMINISTRASI BANK',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '724000',
        'name' => 'BEBAN PAJAK FINAL',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ],
[
        'code' => '725000',
        'name' => 'BEBAN LAIN-LAIN',
        'type' => 'income',
        'category_id' => 1,
        'is_active' => true,
    ]
        ]);
    }
}